### ISSUE TITLE
Signal 9: Killed

### ISSUE THREAD

**Issue by sburlot** [0xced/iOS-Artwork-Extractor#18]
iPhone 4S, iOS 6.1.3, 32G

The app will start scanning all the apps but crashes because of low-memory

> <Warning>: Application 'UIKitApplication:ch.pitaya.iOS-Artwork-Extractor[0x1828]' exited abnormally with signal 9: Killed: 9

Running with Instruments shows the app is using 260M. It seems the app is keeping all images in memory?

PS: I have 341 apps on my device, using 16G of disk space (out of 32G).

![screen shot 2013-06-19 at 15 08 14](https://f.cloud.github.com/assets/47066/674762/e64e0766-d8e1-11e2-94a2-976a22994ff3.jpg)

**Comment by 0xced** [comment]
iOS Artwork Extractor is not intended to be run on a device but in the simulator only, I should probably make that clear in the README.

Indeed, all images are kept in memory, there is no cell reuse and basically the whole code is crap. I’ve thought about improving all this for years but I never did it. So there is a good chance that I will not improve it in the years to come since it's working fine in the simulator. ;-)

**Comment by monjer** [comment]
0，。！
